# Generated by Django 3.0.1 on 2020-01-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('master_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_a', models.CharField(blank=True, max_length=100, null=True)),
                ('option_b', models.CharField(blank=True, max_length=100, null=True)),
                ('option_c', models.CharField(blank=True, max_length=100, null=True)),
                ('option_d', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
                ('solution', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AptitudeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AptitudeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('test_info', models.CharField(blank=True, max_length=500, null=True)),
                ('question_type', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('test_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('time_extend', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Course')),
                ('fk_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo')),
                ('fk_sections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Section')),
                ('fk_semesters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAptitudeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_aptitude_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeQuestion')),
                ('fk_aptitude_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeSession')),
                ('fk_aptitude_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeSet')),
            ],
        ),
        migrations.CreateModel(
            name='PublishTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('test_info', models.CharField(blank=True, max_length=500, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('test_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('time_extend', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_aptitude_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeSet')),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Course')),
                ('fk_faculty_user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo')),
                ('fk_sections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Section')),
                ('fk_semesters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='AptitudeTestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_of', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('fk_aptitude_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeSession')),
                ('fk_aptitude_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeSet')),
                ('fk_user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='aptitudesession',
            name='fk_aptitude_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeSet'),
        ),
        migrations.AddField(
            model_name='aptitudesession',
            name='fk_publish_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.PublishTest'),
        ),
        migrations.AddField(
            model_name='aptitudesession',
            name='fk_user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo'),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='fk_aptitude_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeSet'),
        ),
        migrations.CreateModel(
            name='AllottedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_aptitude_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeSet')),
                ('fk_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptitude.AptitudeQuestion')),
            ],
        ),
    ]
