# Generated by Django 3.0.1 on 2020-01-16 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_forms', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleCompanyAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('placement_status', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_academic_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.AcademicInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_main_address', models.CharField(blank=True, max_length=500, null=True)),
                ('company_location', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_one_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_one_email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_one_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person_two_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_two_email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_two_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('company_other_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('fk_company_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.CompanyType')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAppearanceTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_status', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_appled_company_appearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.AppleCompanyAppearance')),
                ('fk_selection_process_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.SelectionProcessTest')),
                ('fk_user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAppearanceJobTypeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(blank=True, max_length=50, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_job_type', models.ManyToManyField(blank=True, null=True, to='master_forms.JobType')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAppearanceDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=20, null=True)),
                ('start_time', models.TimeField(blank=True, max_length=20, null=True)),
                ('end_time', models.TimeField(blank=True, max_length=20, null=True)),
                ('fk_selection_process_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.SelectionProcessTest')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_interview_location', models.CharField(blank=True, max_length=500, null=True)),
                ('company_visiting_other_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('fk_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.Company')),
                ('fk_company_appearance_date_time_list', models.ManyToManyField(blank=True, null=True, to='placement.CompanyAppearanceDateTime')),
                ('fk_company_appearance_job_type_detail_list', models.ManyToManyField(blank=True, null=True, to='placement.CompanyAppearanceJobTypeDetail')),
            ],
        ),
        migrations.AddField(
            model_name='applecompanyappearance',
            name='fk_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.Company'),
        ),
        migrations.AddField(
            model_name='applecompanyappearance',
            name='fk_company_appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.CompanyAppearance'),
        ),
        migrations.AddField(
            model_name='applecompanyappearance',
            name='fk_user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo'),
        ),
    ]
