# Generated by Django 3.0.1 on 2020-01-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_forms', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(blank=True, max_length=200, null=True)),
                ('assignment_info', models.CharField(blank=True, max_length=2000, null=True)),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('date_post', models.DateField(blank=True, max_length=20, null=True)),
                ('date_final', models.DateField(blank=True, max_length=20, null=True)),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Course')),
                ('fk_sections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Section')),
                ('fk_semesters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Semester')),
                ('fk_subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Subject')),
                ('fk_user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, max_length=20, null=True)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='submitted_assignments/')),
                ('fk_assignment_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_student.Assignment')),
                ('fk_user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_title', models.CharField(blank=True, max_length=200, null=True)),
                ('syllabus_detail', models.TextField(blank=True, null=True)),
                ('syllabus_file', models.FileField(blank=True, null=True, upload_to='syllabus/')),
                ('date_post', models.DateField(blank=True, max_length=20, null=True)),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Course')),
                ('fk_semesters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Semester')),
                ('fk_subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Subject')),
                ('fk_user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_title', models.CharField(blank=True, max_length=200, null=True)),
                ('notes_detail', models.TextField(blank=True, null=True)),
                ('notes_file', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('date_post', models.DateField(blank=True, max_length=20, null=True)),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Course')),
                ('fk_sections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Section')),
                ('fk_semesters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Semester')),
                ('fk_subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Subject')),
                ('fk_user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserInfo')),
            ],
        ),
    ]
