# Generated by Django 3.0.1 on 2020-01-15 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_body', models.TextField(blank=True, null=True)),
                ('audience', models.CharField(blank=True, max_length=20, null=True)),
                ('notice_title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, max_length=20, null=True)),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Course')),
                ('fk_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Section')),
                ('fk_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_forms.Semester')),
            ],
        ),
    ]
